name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        set -x
        which curl
        whcih bzip2
        sudo apt-get -qq update
        sudo apt-get install -y curl bzip2
